#!/usr/bin/env node
/**
 * Generates src/app/core/config/env.generated.ts from .env.
 *
 * Angular compiles the app ahead of time, so there is no run-time environment to
 * read: deployment values have to be baked in at build time. The build reads no
 * .env of its own, so this turns one into a typed module before ng runs.
 *
 * Runs from the prestart, prebuild and pretest npm scripts. The generated file
 * is gitignored; .env.example lists every setting and its default.
 */

import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';

const OUTPUT = 'src/app/core/config/env.generated.ts';

/** Settings, with the defaults used when a variable is unset. */
const SETTINGS = {
  legacyApiUrl: { env: 'PC_LEGACY_API_URL', default: 'https://api.pixelcampus.space' },
  statsApiUrl: { env: 'PC_STATS_API_URL', default: 'https://api.pixelcampus.space' },
  serverHost: { env: 'PC_SERVER_HOST', default: 'pixelcampus.space' },
  bedrockPort: { env: 'PC_BEDROCK_PORT', default: '19132' },
  mapUrl: { env: 'PC_MAP_URL', default: 'https://map.pixelcampus.space/' },
  wikiUrl: { env: 'PC_WIKI_URL', default: 'https://wiki.pixelcampus.space/' },
  discordUrl: { env: 'PC_DISCORD_URL', default: 'https://discord.gg/HQGBwFA3vD' },
  contactUrl: { env: 'PC_CONTACT_URL', default: 'mailto:support@pixelcampus.space' },
  privacyUrl: {
    env: 'PC_PRIVACY_URL',
    default: 'https://wiki.pixelcampus.space/de/impressum-und-datenschutz',
  },
};

if (existsSync('.env')) {
  process.loadEnvFile('.env');
}

const values = Object.fromEntries(
  Object.entries(SETTINGS).map(([key, { env, default: fallback }]) => [
    key,
    process.env[env]?.trim() || fallback,
  ]),
);

const body = `/**
 * Generated by scripts/generate-env.mjs. Do not edit.
 *
 * Values come from .env at build time; see .env.example.
 */
export const ENV = ${JSON.stringify(values, null, 2)} as const;

export type Env = typeof ENV;
`;

await mkdir(dirname(OUTPUT), { recursive: true });

// Only write on change, so the dev server does not rebuild on every start.
const existing = await readFile(OUTPUT, 'utf8').catch(() => null);
if (existing === body) {
  process.exit(0);
}

await writeFile(OUTPUT, body);
console.log(`Wrote ${OUTPUT}`);
