/**
 * Generated by scripts/generate-env.mjs. Do not edit.
 *
 * Values come from .env at build time; see .env.example.
 */
export const ENV = {
  "legacyApiUrl": "",
  "statsApiUrl": "",
  "serverHost": "pixelcampus.space",
  "bedrockPort": "19132",
  "mapUrl": "https://map.pixelcampus.reutlingen.university/",
  "wikiUrl": "https://wiki.pixelcampus.space/",
  "discordUrl": "https://discord.com/invite/hwHmChvdJT",
  "contactUrl": "mailto:MAKERS@reutlingen.university",
  "privacyUrl": "https://stupa.reutlingen.university/datenschutzerklaerung/"
} as const;

export type Env = typeof ENV;
